// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5JkFVEXGSzFHzAuqEzuar4bI1QHXLEA',
    appId: '1:430389503426:android:4a530ae30967aadf40625b',
    messagingSenderId: '430389503426',
    projectId: 'aurora-2b8f4',
    storageBucket: 'aurora-2b8f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRf05wXz6VjnXYpEQk_d23NP83Tw00S4Q',
    appId: '1:430389503426:ios:8d3bff4735e77f3040625b',
    messagingSenderId: '430389503426',
    projectId: 'aurora-2b8f4',
    storageBucket: 'aurora-2b8f4.firebasestorage.app',
    androidClientId: '430389503426-lc31f5jhnmc59b392j0ttkjg5u26bb86.apps.googleusercontent.com',
    iosClientId: '430389503426-asbj9uauck3k0qbhprg4p9v7dpjefn13.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiTherapyTeteocan',
  );
}
